version: '3.8'

services:
  cashflow-app:
    build: .
    container_name: cashflow-app
    ports:
      - "5002:80"
    env_file:
      - ./core/.env
    volumes:
      - ./core/storage:/var/www/html/core/storage
      - ./uploads:/var/www/html/uploads
    restart: unless-stopped
    networks:
      - cashflow-network

  

networks:
  cashflow-network:
    driver: bridge

# volumes:
#   mssql_data: